services:


  kafka:
    image: apache/kafka:4.0.1
    container_name: kafka
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
  
  topic-creator:
      image: apache/kafka:4.0.1
      depends_on:
        - kafka
      entrypoint: ["/bin/bash","-lc"]
      command: |
        "
        sleep 10;
        /opt/kafka/bin/kafka-topics.sh --create --topic BoxOffice --bootstrap-server kafka:9092
        
        "
  # =========================
  # GROUP: SCRAPING
  # =========================
  scraping:
    profiles: ["scraping"]
    container_name: scraping
    build: 
      context: ./WebScraping
    networks:
      - appnet
    # Se vuoi vedere subito i cambi senza rebuild (sviluppo)
    volumes:
      - ./WebScraping:/app

networks:
  appnet:
    driver: bridge
